---
version: "3"

vars:
  goversion:
    sh: go env GOVERSION
  toolchain: '{{.goversion}}+auto'

env:
  CGO_ENABLED: 0

tasks:
  default:
    desc: "Everything"
    cmds:
      - go fmt ./...
      - goimports -w .
      - goimports-reviser -imports-order std,general,company,project,blanked,dotted -company-prefixes github.com/titpetric/ ./...
      - go install ./cmd/...
      - etl version

  up:
    deps: ['build']
    desc: "Bring up an ETL instance for a test"
    cmds:
      - docker compose build
      - docker compose up -d --wait

  down:
    desc: "Bring down the ETL instance"
    cmds:
      - docker compose down --remove-orphans

  build:
    desc: "Build etl binary for docker image"
    cmds:
      - go build ./cmd/...

  setup:
    desc: "Install dev tooling"
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/incu6us/goimports-reviser/v3@latest

  test:
    desc: "Format, lint, test, and build"
    env:
      CGO_ENABLED: 1
      GOTOOLCHAIN: '{{.toolchain}}'
    cmds:
      - goimports -w .
      - go fmt ./...
      - go mod tidy
      - go test -bench=. -benchtime 1s -race -count 1 -cover -coverpkg=./... -coverprofile=pkg.cov ./...
      - go build ./cmd/...

  test:cover:
    desc: "Run tests and generate documentation/coverage reports"
    env:
      CGO_ENABLED: 1
    deps: ['test']
    cmds:
      - task: cover

  test:test-petstore:
    desc: "Run petstore integration tests"
    dir: tests/petstore
    cmds:
      - task

  test:test-users:
    desc: "Run users integration tests"
    dir: tests/users
    cmds:
      - task

  test:all:
    desc: "Run all integration tests"
    cmds:
      - task test:test-petstore
      - task test:test-users

  cover:
    desc: "Generate documentation and coverage reports"
    cmds:
      - go-fsck extract . --include-sources
      - schema-gen extract --include-unexported -i ./server/config/config.go -o config.schema.json --pretty-json
      - schema-gen markdown -i config.schema.json -o docs/config.md --root Config --title "# Configuration"
      - go-fsck extract --pretty-json ./...
      - go tool cover -func=pkg.cov | summary coverfunc --json > pkg.cov.json
      - go-fsck coverage -c pkg.cov.json -o go-fsck.json
      - go-fsck coverage --template=docs/testing-coverage.md.tpl -v > docs/testing-coverage.md
      - perl -pi -e 's/github.com\/titpetric/titpetric/g' docs/testing-coverage.md
      - rm -f config.schema.json
