---
version: "3"

env:
  CGO_ENABLED: 0

tasks:
  default:
    desc: "Everything"
    cmds:
      - go fmt ./...
      - goimports -w .
      - goimports-reviser -imports-order std,general,company,project,blanked,dotted -company-prefixes github.com/titpetric/ ./...
      - go install ./cmd/...
      - etl version

  up:
    deps: ['build']
    desc: "Bring up an ETL instance for a test"
    cmds:
      - docker compose build
      - docker compose up -d --wait

  down:
    desc: "Bring down the ETL instance"
    cmds:
      - docker compose down --remove-orphans

  build:
    desc: "Build etl binary for docker image"
    cmds:
      - go build ./cmd/...

  setup:
    desc: "Install dev tooling"
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/incu6us/goimports-reviser/v3@latest

  test:
    desc: "Format, lint, test, and build"
    env:
      CGO_ENABLED: 1
    cmds:
      - goimports -w .
      - go fmt ./...
      - go mod tidy
      - go test -race ./...
      - go build ./cmd/...

  test:test-petstore:
    desc: "Run petstore integration tests"
    dir: tests/petstore
    cmds:
      - task

  test:test-users:
    desc: "Run users integration tests"
    dir: tests/users
    cmds:
      - task

  test:all:
    desc: "Run all integration tests"
    cmds:
      - task test:test-petstore
      - task test:test-users
