---
version: "3"

includes:
  git: Taskfile.git.yml
  ingest-git-repo:
    taskfile: ingest-git-repo/Taskfile.yml
    dir: ./
  schema-gen:
    taskfile: schema-gen/Taskfile.yml
    dir: ./

vars:
  repository: '{{.repository | default "git@github.com:TykTechnologies/tyk.git" }}'
  database: '{{.database | default "file:etl.db" }}'

tasks:
  default:
    cmds:
      - task: generate
      - task: ingest

  generate:
    cmds:
      - task: generate:model

  generate:model:
    vars:
      args: --db-driver sqlite --db-dsn {{.database}}
    cmds:
      - mig migrate {{.args}} --migrate-path internal/migrations --project sqlite --apply --verbose
      - mig gen {{.args}} --lang=go --go.fill-json --schema=model --output internal/model
      - go install ./cmd/...

  ingest:
    cmds:
      - defer:
          task: git:reset
      - task ingest-git-repo | etl commit create
      # TODO: loop through ETL jobs, per commit, restore output
      - task schema-gen

  clean:
    cmds:
      - rm -f etl.db outputs/
