---
version: "3"

tasks:
  default:
    desc: "Run everything"
    vars:
      duration: 10s
      args: -memprofile memprofile.out -cpuprofile profile.out
    cmds:
      - task: lint
      - go test -count=1 -cover -coverpkg=./... -coverprofile=pkg.cov -v ./...
      - task: cover

  bench:
    desc: "Run benchmarks"
    cmds:
      - go test -gcflags=all=-l -count=1 -bench=. -v -cover -coverpkg=./... -coverprofile=pkg.cov -benchtime={{.duration}} -benchmem {{.args}} ./loader

  lint:
    desc: "Run linters"
    cmds:
      - goimports -w .
      - go mod tidy
      - go fmt ./...
      - schema-gen extract -o - | schema-gen lint -i -

  cover:
    desc: "Show source coverage"
    aliases: [coverage, cov]
    cmds:
      - go tool cover -func=pkg.cov

  uncover:
    desc: "Show uncovered source"
    cmds:
      - uncover pkg.cov

  setup:
    desc: "Set up required tooling"
    cmds:
      - go install github.com/gregoryv/uncover/cmd/uncover@latest
      - go install github.com/titpetric/exp/cmd/schema-gen@latest
